//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBreakDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecargoPersonal
    {
        public int IdRecargoP { get; set; }
        public int IdTipoEvento { get; set; }
        public string PersonalAdicional { get; set; }
        public double Recargo { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
    
        public virtual TipoEvento TipoEvento { get; set; }
    }
}
